### PR TITLE
Update to Feather Icon v4.21.0

### PR DESCRIPTION
**Pull request by abathz**
Adding icon codesandbox, column, figma, mouse-pointer, pen-tool, hexagon and x-octagon

### CODE REVIEW

**Comment by juanprietob** [comment]
I was pulling my hair until I noticed the columns icon is not included yet. 
This PR would make a great addition.

**Comment by abathz** [comment]
thanks a lot! i think you should merge this PR as soon as possible!

**Comment by domino14** [comment]
merge pls

**Comment by domino14** [comment]
please?

**Comment by carmelopullara** [comment]
Version 2.0.1 is out, with all the latest icons and support for tree-shaking.

**Pull request closed without merging**
