### PR TITLE
Use forwardRef on function components

### PR DESCRIPTION
**Pull request by pkrawc**
`Function components cannot be given refs.`

### CODE REVIEW

**Comment by pkrawc** [comment]
@carmelopullara is there a chance this will be merged? This should make these components easier to use in a lot of different situations.

**Comment by katywings** [comment]
+1

(btw @pkrawc thanks for the cool pr :))

**Comment by carmelopullara** [comment]
Thanks for the pr, @pkrawc! Just merged.

**Comment by pkrawc** [comment]
No problem. Happy to help, @carmelopullara . Let me know if there are other things you want done around the project.

**Pull request merged**
