### PR TITLE
Add prop to set strokeWidth

### PR DESCRIPTION
**Pull request by grubersjoe**
I'd like to be able to set the `strokeWidth` of the SVGs with a component property. This PR implements this.

### CODE REVIEW

**Comment by pascalpp** [comment]
@carmelopullara Your thoughts on this PR?

**Comment by 1pxone** [comment]
Feature needed :)

**Comment by pascalpp** [comment]
if anyone is waiting on this, you can do it without the prop using the `stroke-width` property in CSS instead. e.g.

```css
.my-component svg {
  stroke-width: 3;
}
```

(that selector will be different depending on the structure of your app.)

**Comment by Julianus01** [comment]
Thanks for the workaround till then @pascalpp.
Using the strokeWidth prop would be much more elegant though and everything in one place.
Surprised this wasn't implemented from the get go, but happy there is a PR for it :D

**Comment by MiLeung** [comment]
I am able to use the `strokeWidth` prop already without this PR? `"react-feather": "2.0.4"`

**Comment by grubersjoe** [comment]
Oh boy... @MiLeung is right, _all_ SVG properties are already supported. How did I miss this :see_no_evil: :smile:.

**Comment by MiLeung** [comment]
Although one issue I just noticed is icons with thicker stroke-widths might be cut off.

Screen Shot 2020-04-17 at 4 38 21 PM

**Pull request closed without merging**
